config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :books
  root 'welcome#index'

  get 'signup'  => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  resources :sessions

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # find the require_user method in application_controller.rb
  before_action :require_user, only: [:index, :show]

  def index
    bookParams = params[:book]
    if (bookParams)
      books = Book.where(title: bookParams[:title])
    else
      books = []
      for i in 1..5
        books.push(Book.find(i))
     end
    end
    @books = books
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<h1>Search Results</h1>

<div class="book-grid">
  <%= @books.each do |book| %>
    <%= link_to book_path(book) do %>
      <div>
        <p><%= book.title %></p>

        <% if book.author != '' %>
          <p>By: <%= book.author %></p>
        <% end %>

        <% if book.isbn13 != '' %>
          <p>ISBN13: <%= book.isbn13 %></p>
        <% end %>

        <% if book.image != '' %>
          <%= image_tag(book.image) %>
        <% end %>

      </div>
    <% end %>
  <% end %>
</div>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<%= image_tag(@book.image)%>
<div>
  <p>Author: <%= @book.author %></p>
  <p>Strand Bookstore Price: $<%= @book.price / 100.00 %></p>
  <p>Format: <%= @book.format %></p>
  <p>ISBN13: <%= @book.isbn13 %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storytime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag params[:controller] %>
  </head>

  <body>
    #the following will display login/signup and logout buttons depending on if
    #a current_user is associated with the session
    <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "Login", 'login' %></a></li>
        <li><%= link_to "Signup", 'signup' %></a></li>
      </ul>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>
    <%= form_for @user do |f|%>
      First Name: <%= f.text_field :first_name %>
      Last Name: <%= f.text_field :last_name %>
      Email: <%= f.text_field :email%>
      Password: <%= f.password_field :password %>
      <%= f.submit %>
    <% end %>

    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Storytime</h1>
<h3>Search for a book</h3>
<%= form_with scope: :book, url: books_path, method: :get, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>

  <p>
  <%= form.label :isbn13 %><br>
  <%= form.text_field :isbn13 %>
</p>

  <p>
    <%= form.submit %>
  </p>
  <h4>Not sure what to search for first? Try looking for the title "Sea Escape"</h4>
<% end %>